before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: mpyzSsUSBcDOQC2bMQtdOdgOeIy5ZB3ttP8qpTFI2eznGtydW4aNLRACBw89EwtRbU5iRDkzl3cakfmNDRRTL5fR8xA5lwC+3NSGxK9y36gNMIhVkB1w42G7lu/vccl7UI/i1qHNwes+T5ynVvEMKDReGbpwidly3cgMukTk7scE7cVvmD6K5HUUjYU26Qb8PhRZ/jKermztGK3qQA0srElm6M4HR5bA6l7pkhm1LARJHpAKiT7uIYXrZfY+XF3w2Z25hV6u9OhpcmroX8mlcQ85KBEZzLGnIRZ1icdXD8aHJmZKtYvDjBeiCBgECxVWtNuHF38jeBV+OY/oOg+Enmo1Ts3vW0KykeHVLgn6eFnn1exIfj4LTKSrSaET5O/ep3ynjF14Z6HfQmdTneuuZGP/nNVEWrtkmTFymwR6rahkVmEeCRLRN5rc1UgeEf577xsvgz5vubXNg3cJ56q0zJ6PdOr2eS/pesypAd9chUTExG20rwejyTKeI3V626yZ+Nq/Ti9/osd/I1efmRBjzuoaTUMH6m2lB5wyIJCBLPz1qoQ9bM2iJhDoACZ2rhOYkApH+2Ct2OwJlLQtWdWkh07McrMw/FDEw/p+iuSzPg8wt93sHIwGa+YzR70X6DW6AaHaDmt45BgGy8swfVJ1JX+jRpOUpmSCgxT9jK4DbBY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
